### ISSUE TITLE
Unable to send message to a new contact (after the first one)

### ISSUE THREAD

**Issue by jflebeau** [adc17/msn-lives-again#1]
My initial test that worked fined (incoming and outgoing), then I couldn't send a message to a new conversation (either one created from the client or one created automatically from an incoming message). 

Error reported in the console : POST http://localhost:3000/sms/outgoing 400 (Bad Request)

**Comment by AlexChalk** [comment]
Hi, so to confirm, you get this error when sending messages to the second contact added to the app, but not the first?

I can't reproduce this error on my end, but a 400 suggests the api isn't getting all the data it needs to send a message—this is most likely a problem with the contact data.

Could you send me a step-by-step walkthrough to reproduce the problem, starting from the address to which you first navigate in your browser, and including everything you click/type up to when the error occurs?
